old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
    consumers:
        broker_check_command:
            connection:       default
            exchange_options: { name: 'tj.v1.broker_check_command', type: direct }
            queue_options:    { name: 'tj.v1.broker_check_command'}
            callback:         App\Consumer\BrokerCheckCommandConsumer
